#!/usr/bin/env bash

folders="${FOLDERS:-$PLUGIN_FOLDERS}"
cache_bucket="${BUCKET:-$PLUGIN_BUCKET}"
mode="${MODE:-$PLUGIN_MODE}"
key="${PLUGIN_KEY:-$DRONE_REPO/$DRONE_BRANCH}"
filename="${PLUGIN_FILENAME:-cache}"
region="${AWS_REGION:-$PLUGIN_REGION}"

set -e

if [[ -z "$cache_bucket" ]]; then
  echo "-- Error: no bucket specified"
  exit 1
fi

if [[ -z "$region" ]]; then
  echo "-- Error: no region specified"
  exit 1
fi

set +e

case $mode in
    pull)
      echo "-- Pulling cache from S3..."

      cd / && gof3r get -b $cache_bucket -k $key/$filename.tar \
        --endpoint=s3-$region.amazonaws.com | tar -xf -
    ;;
    push)
      echo "-- Pushing cache to S3..."

      cdirs=""
      for f in $(echo $folders | tr -d '[[:space:]]' | tr "," "\n"); do
        if [ -d $PWD/$f ]; then
          cdirs="$cdirs $PWD/$f"
        fi
      done

      tar -cf - $cdirs | gof3r put -b $cache_bucket -k $key/$filename.tar \
        -m x-amz-server-side-encryption:AES256 --endpoint=s3-$region.amazonaws.com
    ;;
    *)
      echo "-- Supported modes:
              pull - restore cache from S3.
              push - cache in S3.
            "
    ;;
esac

echo "-- S3 cache $mode done!"
