#!/usr/bin/env bash
set -e

env_file="${PLUGIN_ENV_FILE:-.env}"
if [[ -f "${env_file}" ]]; then
  source "${env_file}"
fi

folders="${FOLDERS:-$PLUGIN_FOLDERS}"
cache_bucket="${BUCKET:-$PLUGIN_BUCKET}"
mode="${MODE:-$PLUGIN_MODE}"
key="${PLUGIN_KEY:-$DRONE_REPO/$DRONE_BRANCH}"
keys=${PLUGIN_KEYS}
region="${AWS_REGION:-$PLUGIN_REGION}"
overwrite="${PLUGIN_OVERWRITE:-"true"}"
s3_full_path=$(echo "s3://${cache_bucket}/${key}.tar.gz" | envsubst)

if [[ -z "$cache_bucket" ]]; then
  echo "-- Error: no bucket specified"
  exit 1
fi

if [[ -z "$region" ]]; then
  echo "-- Error: no region specified"
  exit 1
fi

case $mode in
    pull)
      echo "-- Pulling cache from S3..."

      if [[ -z ${keys} ]]; then
        if aws --region=${region} s3 ls ${s3_full_path} > /dev/null 2>&1; then
          echo "found in cache: ${s3_full_path}"
          cd / && aws --region=${region} s3 cp ${s3_full_path} - | tar -xzf -
        else
          echo "${s3_full_path} doesn't exists"
        fi
      else
        for key in $(echo ${keys} | sed "s/,/ /g"); do
          s3_full_path=$(echo "s3://${cache_bucket}/${key}.tar.gz" | envsubst)
          if aws --region=${region} s3 ls ${s3_full_path} > /dev/null 2>&1; then
            echo "found in cache: ${s3_full_path}"
            cd / && aws --region=${region} s3 cp ${s3_full_path} - | tar -xzf -
            echo "-- S3 cache $mode done!"
            exit 0
          else
            echo "${s3_full_path} doesn't exists"
          fi
        done
      fi
    ;;

    push)
      echo "-- Pushing cache to S3..."

      if [[ ${overwrite} == "false" ]] && aws --region=${region} s3 ls ${s3_full_path} > /dev/null 2>&1; then
        echo "${s3_full_path} already exists"
        exit 0
      else
        tar -czf - ${folders//,/ } | aws --region=${region} s3 cp --sse aws:kms - ${s3_full_path}
      fi
    ;;

    *)
      echo "-- Supported modes:
              pull - restore cache from S3.
              push - cache in S3.
            "
    ;;
esac

echo "-- S3 cache $mode done!"
